helmDefaults:
  kubeContext: keda-rabbitmq
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    createNamespace: true
    namespace: cert-manager
    version: 1.15.2
    set:
      - name: crds.enabled
        value: true
  - name: rabbitmq-cluster-operator
    chart: bitnami/rabbitmq-cluster-operator
    version: 4.3.14
    needs:
      - cert-manager/cert-manager
  - name: keda
    chart: kedacore/keda
    createNamespace: true
    namespace: keda
  - name: trafik
    chart: traefik/traefik
    version: 30.0.2
    namespace: traefik
    createNamespace: true
    values:
      - traefik/values.yaml
